---
project: deblur_gan
experiment_desc: fpn
dataroot_train: /home/tetianka/Documents/datasets/GOPRO_original
dataroot_val: /home/tetianka/Documents/datasets/GOPRO_original
phase: train
warmup_num: 3
model:
    g_name: fpn_mobilenet
    blocks: 9
    d_name: patch_gan
    d_layers: 3
    content_loss: l1
    feature_loss: perceptual
    disc_loss: ragan
    content_coef: 0.5
    feature_coef: 0.006
    adv_coef: 0.001
    learn_residual: True
    norm_layer: instance
    dropout: True  
num_epochs: 100
num_workers: 4
batch_size: 4
image_size: [256, 256]
fineSize: 256
dataset: 
    task: deblur
optimizer: 
    name: adam
    lr: 0.0001
scheduler:
    name: linear
    start_epoch: 50
    min_lr: 0.0000001

